sudo: required

env:
  global:
    - GO111MODULE=on

services:
  - docker

stages:
  - test
  - versioning
  - chart

jobs:
  include:
    - stage: test
      language: node_js
      node_js: "10"
      before_install:
        - curl -L https://git.io/get_helm.sh | bash
        - helm init --client-only
      script:
        - helm lint .
    - stage: versioning
      language: node_js
      node_js: "10"
      install:
        - npm install -g semantic-release @semantic-release/release-notes-generator @semantic-release/commit-analyzer @semantic-release/changelog @semantic-release/github @semantic-release/git
      if: branch = master
      script:
        - semantic-release
    - stage: chart
      language: minimal
      if: branch = master
      env:
        - NAME=fusionauth
        - TEAM=ninjaneers-team
        - REPOSITORY=charts
        - VERSION=1.0.0
        - EMAIL=charts@ninjaneers.de
      before_install:
        - curl -L https://git.io/get_helm.sh | bash
        - git pull
        - helm init --client-only
        - VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)
      script:
        - helm lint .
        - helm dep update
        - helm package . --version=$VERSION
        - ./.ci/update_chart.sh
        # push it to fusionauth chart repository
        - TEAM=FusionAuth ./.ci/update_chart.sh