dependencies:
  - name: elasticsearch
    version: 7.5.2
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: postgresql
    version: 8.1.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled