dependencies:
  - name: elasticsearch
    version: 6.8.6
    repository: https://helm.elastic.co
  - name: postgresql
    version: 8.1.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled