# Default values for fusionauth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

elasticsearch:
  enabled: true
  image:
    tag: 6.8.6
  master:
    name: master

postgresql: 
  # if enabled = false u need to set data.database.host
  enabled: true
  imageTag: 9.6.15
  postgresqlUsername: localhost
  postgresqlPassword: localhost

image:
  repository: fusionauth/fusionauth-app
  tag: 1.14.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9011

database:
  # if empty {{- .Release.Name -}}-postgresql will be used
  host: ""
  port: 5432
  name: fusionauth
  user: localhost
  password: localhost
  root:
    user: localhost
    password: localhost

search:
  protocol: http
  host: ""
  port: 9200
  # user: ""
  # password: ""
  
environment: 
# Database env DATABASE_USER, DATABASE_PASSWORD, DATABASE_ROOT_USER, DATABASE_ROOT_PASSWORD, DATABASE_URL will be 
# defined in data.database
  FUSIONAUTH_MEMORY: 256M
  # FUSIONAUTH_API_KEY: test
# kickstart:
  # It's important to name your kickstart config kickstart.json
  # kickstart.json: |
  #    {
  #      "variables":{
  #        "apiKey": "#{ENV.FUSIONAUTH_API_KEY}"
  #      },
  #      "apiKeys": [{
  #        "key": "${apiKey}"
  #      }],
  #      "requests": [ {
  #        "method": "POST",
  #        "url": "/api/email/template/0502df1e-4010-4b43-b571-d423fce978b2",
  #        "body": {
  #          "emailTemplate": {
  #            "defaultFromName": "No Reply",
  #            "defaultSubject": "Setup your password",
  #            "defaultHtmlTemplate": "@{setup-password.html}",
  #            "defaultTextTemplate": "@{setup-password.txt}",
  #            "fromEmail": "no-replay@piedpiper.com",
  #            "name": "Setup Password"
  #          }
  #        }
  #      }]
  #    }
  # setup-password.html: |
  #    <div>Test</div>
  # setup-password.txt: |
  #    Hallo

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}